blog/urls.py
from django.urls import path
from .views import IndexView,UserBlogView,BlogView,CreateBlogView,DeleteBlogView,UpdateBlogView

app_name='blog'

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('userblogs/<path:username>',UserBlogView.as_view(),name='userblogs'),
    path('blog/<int:pk>/<path:username>',BlogView.as_view(),name='blog'),
    path('blogdelete/<int:pk>',DeleteBlogView.as_view(),name='delete'),
    path('blogupdate/<int:pk>',UpdateBlogView.as_view(),name='update'),
    path('createblog',CreateBlogView.as_view(),name='createblog')
]

blogpost/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('account/',include('account.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField

CROP_SETTINGS = {'size': (1600, 900), 'crop': 'smart'}

class Blog(models.Model):
    id=models.BigAutoField(primary_key=True)
    blogger=models.ForeignKey(User,related_name='blogs',on_delete=models.CASCADE)
    title=models.CharField(max_length=256)
    description=models.CharField(max_length=256)
    body=models.TextField()
    datetime=models.DateTimeField()
    image=ThumbnailerImageField(upload_to='blogimage',blank=True,resize_source=CROP_SETTINGS)
    def __str__(self):
        return "{0} {1}".format(self.blogger.username,self.title)

class Comment(models.Model):
    id=models.BigAutoField(primary_key=True)
    blogger=models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE)
    blog=models.ForeignKey(Blog,related_name='comments',on_delete=models.CASCADE)
    text=models.CharField(max_length=256)
    datetime=models.DateTimeField()
    def __str__(self):
        return "{0} {1} {2} {3}".format(self.blogger.username,self.blog.title,self.text,self.datetime)

blog/forms.py
from django import forms
from .models import Blog

class CreateBlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=('title','description','image','body')
        labels={
            'title':'',
            'description':'',
            'image':'',
            'body':'',
        }
        widgets={
            'title':forms.TextInput(attrs={
                'class':'form-control border-input',
                'placeholder':'Blog Title'}),
            'description':forms.TextInput(attrs={
                'class':'form-control border-input',
                'placeholder':'Blog Description'}),
            'image':forms.FileInput(attrs={
                'class':'form-control border-input',
                'placeholder':'Blog Image'}),
            'body':forms.Textarea(attrs={
                'class':'editable form-control border-input text-area-resize-disable',
                'placeholder':'Blog Body',
                'rows':'10'}),
        }

blog/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.views import View
from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .models import Blog,Comment
from .forms import CreateBlogForm

class IndexView(ListView):
    model = Blog
    template_name = 'index.html'
    context_object_name = 'objects'
    queryset = Blog.objects.all().order_by('-datetime')[:10]

class UserBlogView(ListView):
    model = Blog
    template_name = 'userblogs.html'
    context_object_name = 'userblogs'
    def get(self,request,username,*args,**kwargs):
        usr=get_object_or_404(User,username=username)
        return render(request,self.template_name,
            {self.context_object_name:Blog.objects.filter(blogger=usr).order_by('-datetime'),'userdetail':usr})

class BlogView(DetailView):
    model = Blog
    template_name = 'blog.html'
    context_object_name = 'blog'
    def get(self,request,pk,username,*args,**kwargs):
        usr=get_object_or_404(User,username=username)
        return render(request,self.template_name,{self.context_object_name:Blog.objects.get(id=pk),
                'otherblogs':Blog.objects.filter(blogger=usr).order_by('-datetime').exclude(id=pk)[:10],
                'comments':Comment.objects.filter(blog=Blog.objects.get(id=pk)).order_by('-datetime'),
                'current_time':datetime.now()})
    @method_decorator(login_required)
    def post(self,request,pk,username,*args,**kwargs):
        comment=Comment(blogger=request.user,blog=Blog.objects.get(id=pk),
            text=request.POST['comment'],datetime=datetime.now())
        comment.save()
        usr=get_object_or_404(User,username=username)
        return render(request,self.template_name,{self.context_object_name:Blog.objects.get(id=pk),
                'otherblogs':Blog.objects.filter(blogger=usr).order_by('-datetime').exclude(id=pk)[:10],
                'comments':Comment.objects.filter(blog=Blog.objects.get(id=pk)).order_by('-datetime'),
                'current_time':datetime.now()})

class CreateBlogView(View):
    template_name = "createblog.html"
    @method_decorator(login_required)
    def get(self,request):
        return render(request,self.template_name,{'form':CreateBlogForm()})
    @method_decorator(login_required)
    def post(self,request):
        form=CreateBlogForm(request.POST,request.FILES)
        if(form.is_valid()):
            obj=form.save(commit=False)
            obj.blogger=request.user
            obj.datetime=datetime.now()
            obj.image=form.cleaned_data['image']
            obj.save()
            return HttpResponseRedirect(reverse('blog:userblogs',kwargs={'username':request.user.username}))
        else:
            return render(request,self.template_name,{'form':form})

class UpdateBlogView(View):
    template_name = "updateblog.html"
    @method_decorator(login_required)
    def get(self,request,pk):
        blog=get_object_or_404(Blog,id=pk)
        return render(request,self.template_name,{'form':CreateBlogForm(instance=blog),'blogimg':blog.image})
    @method_decorator(login_required)
    def post(self,request,pk):
        blog=get_object_or_404(Blog,id=pk)
        form=CreateBlogForm(request.POST,request.FILES,instance=blog)
        if(form.is_valid()):
            obj=form.save(commit=False)
            obj.datetime=datetime.now()
            obj.save()
            return HttpResponseRedirect(reverse('blog:userblogs',kwargs={'username':request.user.username}))
        else:
            return render(request,self.template_name,{'form':form})

class DeleteBlogView(DeleteView):
    model=Blog
    context_object_name = 'blog'
    template_name = "deleteblog.html"
    success_url = reverse_lazy("blog:userblogs")
    @method_decorator(login_required)
    def post(self,request,pk):
        post=get_object_or_404(Blog,id=pk)
        if(post.blogger.username==request.user.username and post.title==request.POST["blog_title"]):
            post.delete()
        return HttpResponseRedirect(reverse("blog:userblogs",kwargs={'username':request.user.username}))

blog/templates/blog.html
{% extends "base.html" %}
{% block body %}
    <div class="container p-2" style="margin-top:70px;">
        <a href="{% url 'blog:userblogs' username=blog.blogger.username %}">
        <span class="row text-dark">
            <span class="col-sm-3 text-center py-2">
                <img class="rounded-pill" style="height:100px;width:100px;" 
                src="{{blog.blogger.profile.profile_pic.url}}"/>
            </span>
            <span class="col-sm-9 class-col-sm-9" style="font-weight:bold;font-family: 'Lato', sans-serif;">
                <p>{{blog.blogger.username}}&nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}</p>
                <p>{{blog.blogger.email}}</p>
                <p>{{blog.datetime}}</p>
            </span>
        </span>
        </a>
    </div>
    <div class="container p-3 rounded" style="background:#fff;">
        <p style="font-family: 'Merriweather', serif;font-size:2.5rem;">{{blog.title}}</p>
        <p style="font-family: 'Lora', serif;font-size:1.3rem;opacity:0.8;">{{blog.description}}</p>
        {% if blog.image %}
        <p class="text-center"><img class="img-fluid rounded" src="{{ blog.image.url}}"/></p>
        {% endif %}
        <div class="blog-body" style="font-family: 'Lato', sans-serif;font-size:1.1rem;">
            {{blog.body|safe|linebreaks}}
        </div>
        {% if blog.blogger.username == request.user.username %}
        <div class="py-2">
            <a href="{% url 'blog:delete' pk=blog.id %}"><button class="btn btn-danger rounded mx-2">Delete Post</button></a>
            <a href="{% url 'blog:update' pk=blog.id %}"><button class="btn btn-warning rounded mx-2">Update Post</button></a>
        </div>
        {% endif %}
    </div>
    <div class="container p-3 rounded my-2" style="background:#fff;">
        <p style="font-weight:bold;font-family: 'Lato', sans-serif;font-size:1.5rem;">
            Comments
        </p>
        {% if user.is_authenticated %}
        <div class="row">
            <span class="col-1 text-end px-1">
                <img class="rounded-pill" style="height:30px;width:30px;" src="{{user.profile.profile_pic.url}}"/>
            </span>
            <form method="POST" class="col-11 row">
                {% csrf_token %}
                <p class="col-10"><input class="form-control" type="text" name="comment" placeholder="Add a Comment"></p>
                <p class="col-1"><input type="submit" class="d-none"></p>
            </form>
        </div>
        {% endif %}
        {% for comment in comments %}
            <div class="comment-card my-1">
                <span class="mx-1 pt-2"><a href="{% url 'blog:userblogs' username=comment.blogger.username %}">
                    <img class="rounded-pill" style="height:30px;width:30px;" src="{{comment.blogger.profile.profile_pic.url}}"/>
                </a></span>
                <span class="comment-card-body">
                    <span style="opacity:0.8;">{{comment.blogger.first_name}}&nbsp;{{comment.blogger.last_name}}
                        &nbsp;&nbsp;{{comment.datetime|timesince:current_time}}</span>
                    <span>{{comment.text}}</span>
                    <span></span>
                </span>
            </div>
        {% endfor %}
    </div>
    {% if otherblogs %}
    <div class="container py-2">
        <p style="font-weight:bold;font-family: 'Lato', sans-serif;font-size:1.5rem;">
            More from {{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}
        </p>
        {% for blog in otherblogs %}
        <a href="{% url 'blog:blog' pk=blog.id username=blog.blogger.username %}">
            <div class="blog-card text-dark m-2 row">
                <div class="blog-grid col-lg-8 col-md-6 p-3">
                    <span>
                        <img class="rounded-pill" style="height:30px;width:30px;" src="{{blog.blogger.profile.profile_pic.url}}"/>
                        &nbsp;&nbsp;{{blog.blogger.username}}
                        &nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}
                    </span>
                    <span style="font-family: 'Oswald', sans-serif;font-size:1.8rem;overflow:hidden;">
                        {{blog.title}}
                    </span>
                    <span style="font-family: 'Lato', sans-serif;opacity:0.8;font-size:1.1rem;overflow:hidden;">
                        {{blog.description}}
                    </span>
                    <span style="font-family: 'Montserrat', sans-serif;">
                        {{blog.datetime}}
                    </span>
                </div>
                <div class="col-lg-4 col-md-6">
                    <img class="img-thumbnail" src="{{blog.image.url}}"/>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

blog/templates/createblog.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <div class="container" style="margin-top:90px;">
        <div class="p-3 rounded text-center" style="background:#fff;">
            <label id="bloglabel" class="text-center mb-2" for="id_image">
                <img id="blogimg" class="img-fluid rounded" alt="Input Image" src="{% static 'image404.png' %}"/>
            </label>
            <form id="id_createform" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
            </form>
            <script>
                var editor = new MediumEditor('.editable',{
                    text: 'Enter Blog Body here.',
                    toolbar: {
                        buttons: [
                            'bold',
                            'italic',
                            'h2',
                            'h6',
                            'anchor',
                        ]
                    }  
                });
            </script>
            <div class="text-start">
                <button form="id_createform" class="btn btn-success rounded btn-out mx-2" style="background:#038C7F;" type="submit">Create</button>
                <a href="{% url 'blog:userblogs' username=user.username %}">
                    <button class="btn btn-outline-dark rounded">Cancel</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/deleteblog.html
{% extends "base.html" %}
{% block body %}
    <div class="container p-2" style="margin-top:70px;">
        <a href="{% url 'blog:userblogs' username=blog.blogger.username %}">
        <span class="row text-dark">
            <span class="col-sm-3 text-center py-2"><img class="rounded-pill" style="height:100px;width:100px;" src="{{user.profile.profile_pic.url}}"/></span>
            <span class="col-sm-9 class-col-sm-9" style="font-weight:bold;font-family: 'Lato', sans-serif;">
                <p>{{blog.blogger.username}}&nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}</p>
                <p>{{blog.blogger.email}}</p>
                <p>{{blog.datetime}}</p>
            </span>
        </span>
        </a>
    </div>
    <div class="container p-3 rounded" style="background:#fff;">
        <h1><span style="opacity:0.6;">Delete Post</span> {{blog.title}}</h1>
        <h1 class="text-center" style="color:#adb5bd;font-size:3rem;"><i class="fa-solid fa-trash"></i></h1>
        <p style="font-size:0.8rem;opacity:0.8;">To confirm this, type "<b>{{blog.title}}</b>"</p>
        <p><form method="POST" class="row">
            {% csrf_token %}
            <p class="col-8"><input type="text" class="form-control form-control-md" name="blog_title" placeholder="{{blog.title}}"></p>
            <p class="col-4"><input type="submit" class="btn btn-md btn-danger" value="Delete"></p>
        </form></p>
        <p class="text-center">
            <a href="{% url 'blog:userblogs' username=user.username %}">
                <button class="btn btn-outline-dark">Cancel</button>
            </a>
        </p>
    </div>
{% endblock %}

blog/templates/updateblog.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <div class="container" style="margin-top:90px;">
        <div class="p-3 rounded text-center" style="background:#fff;">
            <label id="bloglabel" class="text-center mb-2" for="id_image">
                {% if blogimg %}
                <img id="blogimg" class="img-fluid rounded" src="{{blogimg.url}}">
                {% else %}
                <img id="blogimg" class="img-fluid rounded" src="{% static 'image404.png' %}">
                {% endif %}
            </label>
            <form id="id_updateform" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
            </form>
            <script>
                var editor = new MediumEditor('.editable',{
                    text: 'Enter Blog Body here.',
                    toolbar: {
                        buttons: [
                            'bold',
                            'italic',
                            'h2',
                            'h6',
                            'anchor',
                        ]
                    }  
                });
            </script>
            <div class="text-start">
                <button form="id_updateform" class="btn btn-success rounded btn-out mx-2" style="background:#038C7F;" type="submit">Update</button>
                <a href="{% url 'blog:userblogs' username=user.username %}">
                    <button class="btn btn-outline-dark rounded">Cancel</button>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/userblogs.html
{% extends "base.html" %}
{% block body %}
    <div class="container p-2" style="margin-top:70px;">
        <span class="row">
            <span class="col-sm-3 text-center py-2"><img class="rounded-pill" style="height:100px;width:100px;" src="{{userdetail.profile.profile_pic.url}}"/></span>
            <span class="col-sm-9 class-col-sm-9" style="font-weight:bold;font-family: 'Lato', sans-serif;">
                <p>{{userdetail.username}}</p>
                <p>{{userdetail.first_name}}&nbsp;{{userdetail.last_name}}</p>
                <p>{{userdetail.email}}</p>
            </span>
        </span>
    </div>
    <div class="container p-2">
        {% for blog in userblogs %}
        <a href="{% url 'blog:blog' pk=blog.id username=blog.blogger.username %}">
        <div class="blog-card text-dark m-2 row">
            <div class="blog-grid col-lg-8 col-md-6 p-3">
                <span>
                    <img class="rounded-pill" style="height:30px;width:30px;" src="{{blog.blogger.profile.profile_pic.url}}"/>
                    &nbsp;&nbsp;{{blog.blogger.username}}
                    &nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}
                </span>
                <span style="font-family: 'Oswald', sans-serif;font-size:1.8rem;overflow:hidden;">
                    {{blog.title}}
                </span>
                <span style="font-family: 'Lato', sans-serif;opacity:0.8;font-size:1.1rem;overflow:hidden;">
                    {{blog.description}}
                </span>
                <span style="font-family: 'Montserrat', sans-serif;">
                    {{blog.datetime}}
                </span>
            </div>
            {% if blog.image %}
            <div class="col-lg-4 col-md-6">
                <img class="img-thumbnail" src="{{ blog.image.url }}"/>
            </div>
            {% endif %}
        </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}