account/urls.py
from django.urls import path
from .views import AccdetailView,LogoutView,SignupView,LoginView,DeleteUserView,ValidateView,ForgotPasswordView

app_name='account'

urlpatterns = [
    path('sign/<path:username>',SignupView.as_view(),name='sign'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('accdetail',AccdetailView.as_view(),name='accdetail'),
    path('delete',DeleteUserView.as_view(),name='delete'),
    path('forgot/<int:getusername>/<slug:slug>',ForgotPasswordView.as_view(),name='forgot'),
    path('<slug:slug>',ValidateView.as_view(),name='validate'),
]

blog/urls.py
from django.urls import path
from .views import IndexView,UserBlogView,BlogView,CreateBlogView,DeleteBlogView,UpdateBlogView

app_name='blog'

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('userblogs/<path:username>',UserBlogView.as_view(),name='userblogs'),
    path('blog/<int:pk>/<path:username>',BlogView.as_view(),name='blog'),
    path('blogdelete/<int:pk>',DeleteBlogView.as_view(),name='delete'),
    path('blogupdate/<int:pk>',UpdateBlogView.as_view(),name='update'),
    path('createblog',CreateBlogView.as_view(),name='createblog')
]

blogpost/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('account/',include('account.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField

CROP_SETTINGS = {'size': (300, 300), 'crop': 'smart'}

class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='profile',on_delete=models.CASCADE,primary_key=True)
    #additional
    token=models.CharField(max_length=256)
    validatetime=models.DateTimeField()
    dob=models.DateField()
    profile_pic=ThumbnailerImageField(upload_to='profile',default="../media/profile/img6Q.png",blank=True,resize_source=CROP_SETTINGS)
    def __str__(self):
        return "{0} {1}".format(self.user.first_name,self.user.last_name)

account/forms.py
from dataclasses import fields
from django import forms
from .models import User,UserProfile
from django.contrib.auth import authenticate

class UserForm(forms.ModelForm):
    cpassword=forms.CharField(label='',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm Password'}))
    def clean(self):
        cleaned_data=super().clean()
        if(cleaned_data['password']!=cleaned_data['cpassword']):
            raise forms.ValidationError("Passwords do not match!")
    class Meta:
        model=User
        fields=('username','password','cpassword','first_name','last_name','email')
        labels={
            'username':'',
            'password':'',
            'first_name':'',
            'last_name':'',
            'email':'',
        }
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'password':forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'})
        }

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name','email')
        labels={
            'first_name':'',
            'last_name':'',
            'email':'',
        }
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'})
        }
        

class UserProfileForm(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=('dob','profile_pic')
        labels={
            'dob':'',
            'profile_pic':''
        }
        widgets={
            'dob':forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Date of Birth','type': 'date'}),
            'profile_pic':forms.FileInput(attrs={'class':'form-control'})
        }

class LoginForm(forms.Form):
    username=forms.CharField(max_length=256,label='',widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password=forms.CharField(max_length=256,label='',widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    def clean(self):
        super().clean()
        usr=authenticate(username=self.cleaned_data['username'],password=self.cleaned_data['password'])
        if(usr and usr.is_active):
            self.cleaned_data['user']=usr
        else:
            if(usr):
                usr.delete()
            raise forms.ValidationError("Incorrect Username/Password")

account/views.py
from django.views import View
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.conf import settings
import blogpost.settings as bsettings
from django.core.mail import send_mail
from uuid import uuid4
from datetime import datetime
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout

from .forms import User,UserProfile,UserForm,UserUpdateForm,UserProfileForm,LoginForm

class SignupView(View):
    template_name = 'sign.html'
    template_name_email = 'email_token.html'
    def token_generator(self,usrname):
        t1=str(uuid4())
        t2=str(hash(usrname))
        t3=str(hash(str(datetime.now())))
        return t1+t2+t3
    def send_email(self,request,fname,dbtoken,email):
        if(request.is_secure()):
            token='https://'+request.get_host()+'/account/'+dbtoken
        else:
            token='http://'+request.get_host()+'/account/'+dbtoken
        msg="Hi {0}\nHere is your account confirmation link:\n{1}\nTeam Diary\n".format(fname,token)
        send_mail("Account confirmation Mail",msg,settings.EMAIL_HOST_USER,[email])
    def get(self,request,username,*args,**kwargs):
        if(username=='abc'):
            usrdata=UserForm()
            usrprofiledata=UserProfileForm()
            return render(request,self.template_name,{'userform':usrdata,'userprofileform':usrprofiledata})
        else:
            usr=get_object_or_404(User,username=username)
            if(usr.is_active):
                return HttpResponseRedirect(reverse('account:login'))
            else:
                usr.profile.validatetime=datetime.now()
                usr.save()
                self.send_email(request,usr.first_name,usr.profile.token,usr.email)
                return render(request,self.template_name_email,{'email':usr.email,'username':usr.username})
    def post(self,request,*args,**kwargs):
        usrdata=UserForm(request.POST)
        usrprofiledata=UserProfileForm(request.POST,request.FILES)
        if(usrdata.is_valid() and usrprofiledata.is_valid()):
            user=usrdata.save()
            user.set_password(user.password)
            user.is_active=False
            user.save()
            userprofile=usrprofiledata.save(commit=False)
            userprofile.user=user
            userprofile.token=self.token_generator(user.username)
            userprofile.validatetime=datetime.now()
            userprofile.save()
            self.send_email(request,user.first_name,userprofile.token,user.email)
            return render(request,self.template_name_email,{'email':user.email,'username':user.username})
        else:
            return render(request,self.template_name,{'userform':usrdata,'userprofileform':usrprofiledata})

class ValidateView(View):
    template_name='validated.html'
    def get(self,request,slug):
        obj=get_object_or_404(UserProfile,token=slug)
        if(obj.user.is_active):
            return HttpResponseRedirect(reverse('account:login'))
        elif((datetime.now()-obj.validatetime).total_seconds()<2000):
            obj.user.is_active=True
            obj.user.save()
            return render(request,self.template_name,{'activated':True,'username':obj.user.username})
        else:
            usrname=obj.user.username
            obj.user.delete()
            return render(request,self.template_name,{'activated':False,'username':usrname})

class LoginView(View):
    form_class = LoginForm
    template_name = 'login.html'
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            usr=form.cleaned_data['user']
            login(request,usr)
            return HttpResponseRedirect(reverse('blog:index'))
        return render(request, self.template_name, {'form': form})

class LogoutView(View):
    @method_decorator(login_required)
    def get(self,request,*args,**kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('blog:index'))

class AccdetailView(View):
    template_name='accdetail.html'
    @method_decorator(login_required)
    def get(self,request,*args,**kwargs):
        userupdateform = UserUpdateForm(instance=request.user)
        userprofileform = UserProfileForm(instance=request.user.profile)
        return render(request,self.template_name,{'userupdateform':userupdateform,'userprofileform':userprofileform})
    @method_decorator(login_required)
    def post(self,request,*args,**kwargs):
        userupdateform=UserUpdateForm(request.POST,instance=request.user)
        userprofileform=UserProfileForm(request.POST,request.FILES,instance=request.user.profile)
        if(userupdateform.is_valid() and userprofileform.is_valid()):
            userupdateform.save()
            userprofileform.save()
        return render(request,self.template_name,{'userupdateform':userupdateform,'userprofileform':userprofileform})

class DeleteUserView(View):
    template_name='delete.html'
    @method_decorator(login_required)
    def get(self,request):
        return render(request,self.template_name)
    @method_decorator(login_required)
    def post(self,request):
        if(request.POST['username']==request.user.username):
            usr=request.user
            usrname=usr.username
            logout(request)
            usr.delete()
            return render(request,self.template_name,{'username':usrname})
        else:
            return HttpResponseRedirect(reverse('account:accdetail'))

class ForgotPasswordView(View):
    template_usr_name='forgotusr.html'
    template_pwd_name='forgotpwd.html'
    template_name='forgot.html'
    def token_generator(self,usrname):
        t1=str(uuid4())
        t2=str(hash(usrname))
        t3=str(hash(str(datetime.now())))
        return t1+t2+t3
    def send_email(self,request,usr):
        usrprofile=get_object_or_404(UserProfile,user=usr)
        usrprofile.token=self.token_generator(usr.username)
        usrprofile.validatetime=datetime.now()
        usrprofile.save()
        if(request.is_secure()):
                token='https://'+request.get_host()+'/account/forgot/0/'+usrprofile.token
        else:
            token='http://'+request.get_host()+'/account/forgot/0/'+usrprofile.token
        msg="Hi {0}\nHere is your password reset link:\n{1}\nTeam Diary\n".format(usr.first_name,token)
        send_mail("Password Reset Request Mail",msg,settings.EMAIL_HOST_USER,[usr.email])
    def get(self,request,getusername,slug):
        if(getusername):
            return render(request,self.template_usr_name)    
        else:
            obj=get_object_or_404(UserProfile,token=slug)
            if((datetime.now()-obj.validatetime).total_seconds()<2000):
                return render(request,self.template_pwd_name,{'username':obj.user.username})
            else:
                return render(request,self.template_name,{'expired':True})
    def post(self,request,getusername,slug):
        if(getusername):
            usr=get_object_or_404(User,username=request.POST['username'])
            self.send_email(request,usr)
            return render(request,self.template_name,{'expired':False,'email':usr.email})
        else:
            obj=get_object_or_404(UserProfile,token=slug)
            obj.user.password=request.POST['password']
            obj.user.set_password(obj.user.password)
            obj.user.save()
            return HttpResponseRedirect(reverse('account:login'))

account/templates/accdetail.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="accdetailcard text-center">
            <div style="background:#0D0D0D;border-radius:5px 5px 0px 0px;">
                <label id="accprofile" style="margin-top:1rem;border-radius: 6rem;" for="id_profile_pic">
                    <img id="accprofileimg" src="{{user.profile.profile_pic.url}}">
                    <i id="camicon" class="fa-solid fa-camera" ></i>
                </label>
            </div>
            <form class="m-2 border-bottom border-1" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{userupdateform.as_p}}
                {{userprofileform.as_p}}
                <input type="submit" class="btn btn-out px-4 text-white" style="background:#027373;" value="Save">
            </form>
            <div>
                <a href="{% url 'account:delete' %}"><button type="button" class="btn btn-outline-danger">Delete Account</button></a>
            </div>
        </div>
    </div>
{% endblock %}

account/templates/delete.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard p-3" style="background: #fff;grid-template-rows:12% 78% 10%;">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            {% if user.is_authenticated %}
            <div class="mt-2">
                <h1>Delete Account</h1>
                <p>Deleting your account will  remove all of your information from our database. This cannot be undone.</p>
                <h1 class="text-center" style="color:#adb5bd;font-size:3rem;"><i class="fa-solid fa-trash"></i></h1>
                <p style="font-size:0.8rem;opacity:0.8;">To confirm this, type "<b>{{user.username}}</b>"</p>
                <p><form method="POST" class="row">
                    {% csrf_token %}
                    <p class="col-8"><input type="text" class="form-control form-control-md" name="username" placeholder="{{user.username}}"></p>
                    <p class="col-4"><input type="submit" class="btn btn-md btn-danger" value="Delete"></p>
                </form></p>
            </div>
            <div class="text-center"><a href="{% url 'account:accdetail' %}">
                <button type="button" class="btn btn-outline-dark px-5 py-1">Cancel</button></a></div>
            {% else %}
            <div class="mt-2">
                <h1>Account Deleted</h1>
                <p>The account with username <b>{{username}}</b> is deleted.</p>
                <h1 class="text-center" style="font-size:3rem;"><i class="fa-solid fa-trash"></i></h1>
            </div>
            <div class="text-center"><a href="{% url 'account:sign' username='abc' %}">
                <button class="btn btn-out px-4 text-white" style="background:#027373;">Sign Up</button>
            </a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

account/templates/email_token.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard p-3" style="background: #fff;">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            <div class="mt-2">
                <h1>Verify your Email</h1>
                <p>We have sent an email to <b>{{email}}</b></p>
                <p>You need to verify your email to continue.</p>
                <p>You can also click the <b>Resend Verification Email</b> button below to have another email sent to you.</p>
            </div>
            <div class="text-center"><a href="{% url 'account:sign' username=username %}"><button class="btn btn-primary px-5 py-1 rounded">Resend Verification Email</button></a></div>
        </div>
    </div>
{% endblock %}

account/templates/forgot.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard p-3" style="background: #fff;">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            <div class="mt-2">
                {% if expired %}
                <h1>Link Expired</h1>
                {% else %}
                <h1>Verify your Email</h1>
                <p>We have sent an email to <b>{{email}}</b></p>
                <p>You need to verify your email to continue.</p>
                {% endif %}
            </div>
            <div class="text-center"><a href="{% url 'account:login' %}">
                <button type="button" class="btn btn-outline-dark px-5 py-1">Back to Login</button>
            </a></div>
        </div>
    </div>
{% endblock %}

account/templates/forgotpwd.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard p-3" style="background: #fff;">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            <div class="mt-2">
                <form method="POST">
                    {% csrf_token %}
                    <label for="pwd" class="form-label"><h3>{{username}}</h3></label>
                    <div class="input-group mb-3">
                        <input id="pwd" name="password" class="form-control" placeholder="Enter password" required type="password"/>
                        <span class="input-group-text"><i class="fa-solid fa-key"></i></span>
                    </div>
                    <input class="btn btn-out text-white" style="background:#027373;" type="submit" value="Submit">
                </form>
            </div>
            <div class="text-center"><a href="{% url 'account:login' %}">
                <button type="button" class="btn btn-outline-dark px-5 py-1">Back to Login</button>
            </a></div>
        </div>
    </div>
{% endblock %}

account/templates/forgotusr.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard p-3" style="background: #fff;">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            <div class="mt-2">
                <form method="POST">
                    {% csrf_token %}
                    <label for="username" class="form-label"><h3>Username</h3></label>
                    <div class="input-group mb-3">
                        <input id="username" name="username" class="form-control" placeholder="abc@123"required type="text"/>
                        <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                    </div>
                    <input class="btn btn-out text-white" style="background:#027373;" type="submit" value="Submit">
                </form>
            </div>
            <div class="text-center"><a href="{% url 'account:login' %}">
                <button type="button" class="btn btn-outline-dark px-5 py-1">Back to Login</button>
            </a></div>
        </div>
    </div>
{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont text-center" style="background:#A9D9D0;">
        <div class="loginformcard py-3 px-2">
            <h1>Login</h1>
            <form class="m-1" style="transform:translateY(0.5rem);" method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="input-group my-3">
                    {{ form.username }}
                    <span class="input-group-text"><i class="fa-solid fa-user"></i></span>
                </div>
                <div class="input-group my-3">
                    {{ form.password }}
                    <span class="input-group-text"><i class="fa-solid fa-key"></i></span>
                </div>
                <input type="submit" class="btn btn-out px-4 text-white" style="background:#027373;" value="Login"/>
            </form>
            <div>
                <p>Forgot password? <a class="font-primary" href="{% url 'account:forgot' getusername=1 slug='forgot'%}">click here</a></p>
                <p>Don't have an account? <a class="font-primary" href="{% url 'account:sign' username='abc'%}">click here</a></p>
            </div>
        </div>
    </div>
{% endblock %}

account/templates/sign.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont" style="background:#F2E7DC;">
        <div class="signupformcard p-2">
            <div style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h2>Sign Up</h2>
                <span style="color: rgba(0, 0, 0, 0.6);">Please fill this form to create an account</span>
            </div>
            <form class="m-1" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{userform.as_p}}
                {{userprofileform.as_p}}
                <input class="btn btn-out text-white" style="background:#027373;" type="submit" value="Register"/>
            </form>
            <div class="text-center">Already have an account? <a class="font-primary" href="{% url 'account:login' %}">click here</a></div>
        </div>
    </div>
{% endblock %}

account/templates/validated.html
{% extends 'base.html' %}
{% block body %}
    <div class="cont bg-light">
        <div class="emailformcard text-center p-3" style="background: #fff;">
            <div class="text-left" style="border-bottom: 1px solid rgba(0, 0, 0, 0.2);">
                <h4><a style="font-family:'Dancing Script',cursive;font-size:35px;color:rgba(0,0,0,0.6);" 
                    alt="Logo" href="{% url 'blog:index' %}">
                    Diary.com
                </a></h4>
            </div>
            <div class="mt-2">
                {% if activated %}
                <h2>Thank You!</h2>
                <p><h1 style="color:#198754;"><i class="fa-solid fa-check"></i></h1></p>
                <p>Your Account with username <b>{{username}}</b> is activated.</p>
                <p>Click on the <b>Login</b> button for login.</p>
                {% else %}
                <h2>Link Expired!</h2>
                <p><h1 style="color:#dc3545;"><i class="fa-solid fa-xmark"></i></h1></p>
                <p>Your Account with username <b>{{username}}</b> is deleted.</p>
                <p>Click on the <b>Sign Up</b> button to create new account.</p>
                {% endif %}
            </div>
            <div class="text-center">
                {% if activated %}
                <a href="{% url 'account:login' %}"><button class="btn btn-success px-5 py-1 rounded">Login</button></a>
                {% else %}
                <a href="{% url 'account:sign' username='abc' %}"><button class="btn btn-primary px-5 py-1 rounded">Sign Up</button></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}