account/urls.py
from django.urls import path
from .views import AccdetailView,LogoutView,SignupView,LoginView,DeleteUserView,ValidateView,ForgotPasswordView

app_name='account'

urlpatterns = [
    path('sign/<path:username>',SignupView.as_view(),name='sign'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('accdetail',AccdetailView.as_view(),name='accdetail'),
    path('delete',DeleteUserView.as_view(),name='delete'),
    path('forgot/<int:getusername>/<slug:slug>',ForgotPasswordView.as_view(),name='forgot'),
    path('<slug:slug>',ValidateView.as_view(),name='validate'),
]

blog/urls.py
from django.urls import path
from .views import IndexView,UserBlogView,BlogView,CreateBlogView,DeleteBlogView,UpdateBlogView

app_name='blog'

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('userblogs/<path:username>',UserBlogView.as_view(),name='userblogs'),
    path('blog/<int:pk>/<path:username>',BlogView.as_view(),name='blog'),
    path('blogdelete/<int:pk>',DeleteBlogView.as_view(),name='delete'),
    path('blogupdate/<int:pk>',UpdateBlogView.as_view(),name='update'),
    path('createblog',CreateBlogView.as_view(),name='createblog')
]

blogpost/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('account/',include('account.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'diary.png' %}">
    <!-- BootStrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
    <!-- Local CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Medium editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link href="https://yabwe.github.io/medium-editor/bower_components/medium-editor/dist/css/themes/beagle.css" rel="stylesheet"/>
    <title>Diary.com</title>
    <style>
        body{background:#ECF0F1}
        .load{
            position:absolute;top:50%;left:50%;transform:translate(-50%, -50%);
            /*change these sizes to fit into your project*/
            width:100px;
            height:100px;
        }
        .load hr{opacity:1;border:0;margin:0;width:40%;height:40%;position:absolute;border-radius:50%;animation:spin 2s ease infinite}
        .load :first-child{background:#A9D9D0;animation-delay:-1.5s}
        .load :nth-child(2){background:#027373;animation-delay:-1s}
        .load :nth-child(3){background:#F2E7DC;animation-delay:-0.5s}
        .load :last-child{background:#0D0D0D}

        @keyframes spin{
        0%,100%{transform:translate(0)}
        25%{transform:translate(160%)}
        50%{transform:translate(160%, 160%)}
        75%{transform:translate(0, 160%)}
        }
    </style>
</head>
<body onload="loader()" style="overflow-x:hidden;" class="bg-light">
    <div class="load">
        <hr/><hr/><hr/><hr/>
    </div>
    <nav class="navbar fixed-top navbar-expand-md text-white" style="background:#0D0D0D;">
        <div class="navbar-header">
            <a class="text-white" style="font-family:'Dancing Script',cursive;font-size:35px;" alt="Logo" href="{% url 'blog:index' %}">
                Diary.com
            </a>
        </div>
        <button class="navbar-toggler text-white" data-bs-toggle="collapse" data-bs-target="#mycollapse">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="mycollapse">
            <div class="container">
                <ul class="navbar-nav float-md-end" style="font-size:20px;">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'blog:userblogs' username=user.username %}">
                        <button class="btn border-2 btn-outline-light w-100 px-4">Blogs</button>
                    </a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'blog:createblog' %}">
                        <button class="btn border-2 btn-outline-light w-100 px-4">Create Blog</button>
                    </a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'account:sign' username='abc' %}">
                        <button type="button" class="btn border-2 btn-outline-light w-100 px-4">Sign Up</button>
                    </a></li>
                    {% endif %}
                    <li class="nav-item dropdown" style="cursor:pointer;">
                        <button class="btn border-2 border-white w-100 nav-link text-white dropdown-toggle" data-bs-toggle="dropdown">
                            {% if user.is_authenticated %}
                            {{user.first_name}}
                            &nbsp;<img src="{{user.profile.profile_pic.url}}" class="rounded" style="width:35px;height:35px;" alt="Profile">
                            {% else %}
                            User
                            &nbsp;<img src="{% static 'img6Q.png' %}" class="rounded" style="width:35px;height:35px;" alt="Profile">
                            {% endif %}
                        </button>    
                        <ul class="dropdown-menu dropdown-menu-end">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'account:logout' %}"><button class="dropdown-item">&nbsp;Logout</button></a></li>
                            <li><a href="{% url 'account:accdetail' %}"><button class="dropdown-item">&nbsp;Account</button></a></li>
                            {% else %}
                            <li><a href="{% url 'account:login' %}"><button class="dropdown-item">&nbsp;Login</button></a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="section" style="display:none;">
        {% block body %}
        <!-- Content goes here -->
        {% endblock %}
    </div>
</body>
<!-- BootStrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
crossorigin="anonymous"></script>
<!-- FontAwesome icons -->
<script src="https://kit.fontawesome.com/2939ec19a4.js" crossorigin="anonymous"></script>
<!-- Local JS -->
<script src="{% static 'script.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="cont">
        <div class="row overflow-hidden" style="height:100%;width:100%;background:#038C7F;">
            <div class="col-lg-4 land-card">
                <span class="land-card-1"><p>Remain Inquisitive</p></span>
                <span class="land-card-2">
                    <p>Discover stories, thinking, and expertise from writers on any topic.</p>
                    <p><a href="{% url 'account:sign' username='abc' %}">
                        <button class="mt-2 btn btn-outline-dark btn-lg border-2 rounded-pill">Start reading</button>
                    </a></p>
                </span>
            </div>
            <div class="col-lg-8"><img class="img-land" src="{% static 'imgld.svg' %}"/></div>
        </div>
    </div>
    <div class="container p-2">
        <p><h4><i class="fa-solid fa-arrow-trend-up"></i>&nbsp;&nbsp;LATEST ON DIARY</h4></p>
        {% for blog in objects %}
        <a href="{% url 'blog:blog' pk=blog.id username=blog.blogger.username %}">
        <div class="blog-card text-dark m-2 row">
            <div class="blog-grid col-lg-8 col-md-6 p-3">
                <span>
                    <img class="rounded-pill" style="height:30px;width:30px;" src="{{blog.blogger.profile.profile_pic.url}}"/>
                    &nbsp;&nbsp;{{blog.blogger.username}}
                    &nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}
                </span>
                <span style="font-family: 'Oswald', sans-serif;font-size:1.8rem;overflow:hidden;">
                    {{blog.title}}
                </span>
                <span style="font-family: 'Lato', sans-serif;opacity:0.8;font-size:1.1rem;overflow:hidden;">
                    {{blog.description}}
                </span>
                <span style="font-family: 'Montserrat', sans-serif;">
                    {{blog.datetime}}
                </span>
            </div>
            {% if blog.image %}
            <div class="col-lg-4 col-md-6">
                <img class="img-thumbnail" src="{{blog.image.url}}"/>
            </div>
            {% endif %}
        </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

templates/userblogs.html
{% extends "base.html" %}
{% block body %}
    <div class="container p-2" style="margin-top:70px;">
        {% for blog in userblogs %}
        <div class="blog-card m-2 row">
            <div class="blog-grid col-lg-8 col-md-6 p-3">
                <span>
                    <img class="rounded-pill" style="height:30px;width:30px;" src="{{blog.blogger.profile.profile_pic.url}}"/>
                    &nbsp;&nbsp;{{blog.blogger.username}}
                    &nbsp;&nbsp;{{blog.blogger.first_name}}&nbsp;{{blog.blogger.last_name}}
                </span>
                <span style="font-family: 'Oswald', sans-serif;font-size:1.8rem;overflow:hidden;">
                    {{blog.title}}
                </span>
                <span style="font-family: 'Lato', sans-serif;opacity:0.8;font-size:1.1rem;overflow:hidden;">
                    {{blog.description}}
                </span>
                <span style="font-family: 'Montserrat', sans-serif;">
                    {{blog.datetime}}
                </span>
            </div>
            <div class="col-lg-4 col-md-6">
                <img class="img-thumbnail" src="{{blog.img.url}}"/>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}